Repository quantopian/libpy, pull requests merged in 2020-07, with the labels that each got.

#174 MAINT: Move sparsehash code to library_wrappers/sparsehash
  Makefile
  README.rst
  docs/source/install.rst
  include/libpy/library_wrappers/sparsehash.h
  tests/library_wrappers/test_sparsehash.cc
  tests/test_any.cc
  tests/test_object_map_key.cc
  tests/test_to_object.cc
  tests/test_utils.h
Labels: maintenance

#177 ENH: Create sequence_to_object
  include/libpy/to_object.h
Labels: enhancement

#183 BLD: bump to latest numpy in builds
  .github/workflows/main.yml
  .github/workflows/release.yml
Labels: build

#185 BLD: build docs on macOS
  .github/workflows/main.yml
  docs/source/tutorial/setup.py
Labels: build

#186 BLD: Have dependabot manage GHA versions
  .github/dependabot.yml
Labels: build

#187 ENH: Autoclass fixes
  include/libpy/autoclass.h
  tests/_test_automodule.cc
  tests/test_autoclass.cc
Labels: bug, enhancement

#179 BLD: Start testing on ubuntu 20.04 LTS
  .github/workflows/main.yml
  MANIFEST.in
  Makefile
  README.rst
  docs/source/install.rst
  etc/Makefile.buildkite
  etc/ld_flags.py
  include/libpy/to_object.h
  tests/test_to_object.cc
Labels: build

#188 REL: 0.2.3
  version
Labels: release

#189 ENH: Inline nullptr instead of using end_method_list
  include/libpy/automodule.h
Labels: enhancement

#196 DOC: Add more documentation on choosing a python on install
  README.rst
  docs/source/install.rst
Labels: documentation

#182 DOC: more tutorial content
  docs/source/appendix.rst
  docs/source/arrays.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/shock-and-awe.rst
  docs/source/tutorial.rst
  docs/source/tutorial/functions.rst
  docs/source/tutorial/libpy_tutorial/arrays.cc
  docs/source/tutorial/libpy_tutorial/function.cc
  docs/source/tutorial/setup.py
  include/libpy/automodule.h
  include/libpy/ndarray_view.h
  libpy/build.py
Labels: documentation
